### PR TITLE
fix url download, cookie bug

### PR DESCRIPTION
**Pull request by jcabdala**
I had problem with download modis and comment in #59 

I solve problem in my local machine but not in my azure server.

I found this script https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+Python  
And it works on any machine.

I replace that code  in downladmodis.py line 639 and now works on the server.

### CODE REVIEW

**Comment by Kavindagunasekara** [comment]
thanks for the information. BTW, replace line 639 to which line number? thanks

**Comment by lucadelu** [comment]
This code is working only with python2 because in python3 there is no more urllib2.

I continue to don't understand why me and other colleagues are able to use pyModis without your changes and other like you or @kalxas are not able....

I will try to merge your changes

**Comment by kalxas** [comment]
Hi @lucadelu 
I was able to make version 2.0.2 work fine for me.
I found out that the problem was a "$" character in my password.
After changing that, everything works fine.

Best,
Angelos

**Comment by lucadelu** [comment]
@kalxas so 2.0.2 is working without this pull request? So the problem seems to be "strange" characters in the password? any idea how to fix it?

**Comment by kalxas** [comment]
@lucadelu yes, 2.0.2 is working without this pull request.
For my precise production server though, I had to use anaconda to make it work.
For the strange characters, I have not yet managed to debug this issue, I got a 403 error.

**Pull request closed without merging**
